// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GreenInspireLib.Models;

[Table("Category")]
public partial class Category
{
    [Key]
    [Column("Category_Id")]
    public int CategoryId { get; set; }

    [Column("Category_Name")]
    [StringLength(100)]
    [Unicode(false)]
    public string CategoryName { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Categories")]
    public virtual ICollection<Newsfeed> Newsfeeds { get; set; } = new List<Newsfeed>();

    public void ValidateCategoryNameLength()
    {
        if (string.IsNullOrEmpty(CategoryName))
        {
            throw new ArgumentOutOfRangeException("Category name cannot be empty");
        }
        if (CategoryName.Length <= 1)
        {
            throw new ArgumentOutOfRangeException("Category name must be longer than 1 character");
        }
        if (CategoryName.Length > 30)
        {
            throw new ArgumentOutOfRangeException("Category name must be shorter than 30 characters");
        }
    }

    public void Validate()
    {
        ValidateCategoryNameLength();
    }
}