// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GreenInspireLib.Models;

[Table("Category")]
public partial class Category
{
    [Key]
    [Column("Category_Id")]
    public int CategoryId { get; set; }

    [Column("Category_Name")]
    [StringLength(100)]
    [Unicode(false)]
    public string CategoryName { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Categories")]
    public virtual ICollection<Newsfeed> Newsfeeds { get; set; } = new List<Newsfeed>();
}