// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GreenInspireLib.Models;

[Table("Company_User")]
public partial class CompanyUser
{
    [Key]
    [Column("Company_User_Id")]
    public int CompanyUserId { get; set; }

    [Required]
    [Column("Company_Name")]
    [StringLength(30)]
    [Unicode(false)]
    public string CompanyName { get; set; }

    [Column("Company_Logo")]
    [MaxLength(1)]
    public byte[] CompanyLogo { get; set; }

    [Column("Company_CVR")]
    public int CompanyCvr { get; set; }

    [Column("Company_Size")]
    [StringLength(30)]
    [Unicode(false)]
    public string CompanySize { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("User_Password")]
    [StringLength(50)]
    [Unicode(false)]
    public string UserPassword { get; set; }

    [Column("Industry_Id")]
    public int IndustryId { get; set; }

    [ForeignKey("IndustryId")]
    [InverseProperty("CompanyUsers")]
    public virtual Industry Industry { get; set; }

    [InverseProperty("CompanyUser")]
    public virtual ICollection<Newsfeed> Newsfeeds { get; set; } = new List<Newsfeed>();

    public void ValidateUserName()
    {
        if (CompanyName == null) throw new ArgumentNullException("Navn skal udfyldes");
        if (CompanyName.Length < 1) throw new ArgumentOutOfRangeException("Navnet skal være mimimum 1 karakter lang");
        if (CompanyName.Length > 25) throw new ArgumentOutOfRangeException("Navnet må max være 25 karaktere");
    }

    public void ValidateCompanyCVR()
    {
        if (CompanyCvr != 8) throw new ArgumentOutOfRangeException("CVR nummer skal være 8 cifre langt");
    }

    public void ValidateCompanySize()
    {
        if (!(CompanySize.Equals("Stor") || CompanySize.Equals("Mellem") || CompanySize.Equals("Lille")))
        {
            throw new ArgumentException("Du skal vælge mellem (Lille, Mellem eller Stor)");
        }
    } 

    public void ValidateLogo()
    {
        if (CompanyLogo == null) throw new ArgumentNullException("Indsæt logo");
    }

    public void ValidateEmail()
    {
        if (Email == null) throw new ArgumentNullException("Udfyld email");
        if (!Email.Contains("@")) throw new ArgumentException("Indeholder ikke @, udfyld email");
    }

    public void ValidatePassword()
    {
        if (UserPassword == null) throw new ArgumentNullException("Udfyld password"); 
        if (UserPassword.Length < 8) throw new ArgumentOutOfRangeException("Passwordet skal være minimum 8 karaktere langt");
    }

    public void Validate()
    {    
        ValidateUserName();
        ValidateLogo();
        ValidateCompanyCVR();
        ValidateCompanySize();       
        ValidateEmail();
        ValidatePassword();       
    }
}