// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GreenInspireLib.Models;

[Table("Company_User")]
public partial class CompanyUser
{
    [Key]
    [Column("Company_User_Id")]
    public int CompanyUserId { get; set; }

    [Required]
    [Column("Company_Name")]
    [StringLength(30)]
    [Unicode(false)]
    public string CompanyName { get; set; }

    [Column("Company_Logo")]
    [MaxLength(1)]
    public byte[] CompanyLogo { get; set; }

    [Column("Company_CVR")]
    public int CompanyCvr { get; set; }

    [Column("Company_Size")]
    [StringLength(30)]
    [Unicode(false)]
    public string CompanySize { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("User_Password")]
    [StringLength(50)]
    [Unicode(false)]
    public string UserPassword { get; set; }

    [Column("Industry_Id")]
    public int IndustryId { get; set; }

    [ForeignKey("IndustryId")]
    [InverseProperty("CompanyUsers")]
    public virtual Industry Industry { get; set; }

    [InverseProperty("CompanyUser")]
    public virtual ICollection<Newsfeed> Newsfeeds { get; set; } = new List<Newsfeed>();
}