// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GreenInspireLib.Models;

public partial class GreenInspireContext : DbContext
{
    public GreenInspireContext()
    {
    }

    public GreenInspireContext(DbContextOptions<GreenInspireContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<CompanyUser> CompanyUsers { get; set; }

    public virtual DbSet<Industry> Industries { get; set; }

    public virtual DbSet<Newsfeed> Newsfeeds { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-3V4HCC3;Initial Catalog=GreenInspire;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Category__6DB38D6EDD7F9DB0");
        });

        modelBuilder.Entity<CompanyUser>(entity =>
        {
            entity.HasKey(e => e.CompanyUserId).HasName("PK__Company___F3DEC318E731E6C8");

            entity.Property(e => e.CompanyLogo).IsFixedLength();

            entity.HasOne(d => d.Industry).WithMany(p => p.CompanyUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Company_U__Indus__398D8EEE");
        });

        modelBuilder.Entity<Industry>(entity =>
        {
            entity.HasKey(e => e.IndustryId).HasName("PK__Industry__1A177418365E3169");
        });

        modelBuilder.Entity<Newsfeed>(entity =>
        {
            entity.HasKey(e => e.NewsfeedId).HasName("PK__Newsfeed__C3F6B9D62D0601B8");

            entity.Property(e => e.NewsfeedImage).IsFixedLength();

            entity.HasOne(d => d.CompanyUser).WithMany(p => p.Newsfeeds)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Newsfeed__Compan__3C69FB99");

            entity.HasMany(d => d.Categories).WithMany(p => p.Newsfeeds)
                .UsingEntity<Dictionary<string, object>>(
                    "NewsfeedCategory",
                    r => r.HasOne<Category>().WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Newsfeed___Categ__4222D4EF"),
                    l => l.HasOne<Newsfeed>().WithMany()
                        .HasForeignKey("NewsfeedId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Newsfeed___Newsf__412EB0B6"),
                    j =>
                    {
                        j.HasKey("NewsfeedId", "CategoryId").HasName("PK__Newsfeed__352D8100FA0AFB19");
                        j.ToTable("Newsfeed_Category");
                        j.IndexerProperty<int>("NewsfeedId").HasColumnName("Newsfeed_Id");
                        j.IndexerProperty<int>("CategoryId").HasColumnName("Category_Id");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}