// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GreenInspireLib.Models;

[Table("Industry")]
public partial class Industry
{
    [Key]
    [Column("Industry_Id")]
    public int IndustryId { get; set; }

    [Required]
    [Column("Industry_Name")]
    [StringLength(50)]
    [Unicode(false)]
    public string IndustryName { get; set; }

    [InverseProperty("Industry")]
    public virtual ICollection<CompanyUser> CompanyUsers { get; set; } = new List<CompanyUser>();
}