// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using static System.Net.Mime.MediaTypeNames;


namespace GreenInspireLib.Models;

[Table("Newsfeed")]
public partial class Newsfeed
{
    [Key]
    [Column("Newsfeed_Id")]
    public int NewsfeedId { get; set; }

    [Column("Newsfeed_Image")]
    [MaxLength(1)]
    public byte[] NewsfeedImage { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Title { get; set; }

    [Required]
    [Column("Newsfeed_Text")]
    [StringLength(500)]
    [Unicode(false)]
    public string NewsfeedText { get; set; }

    [Column("Newsfeed_Timestamp", TypeName = "datetime")]
    public DateTime NewsfeedTimestamp { get; set; }

    [Column("Company_User_Id")]
    public int CompanyUserId { get; set; }

    [ForeignKey("CompanyUserId")]
    [InverseProperty("Newsfeeds")]
    public virtual CompanyUser CompanyUser { get; set; }

    [ForeignKey("NewsfeedId")]
    [InverseProperty("Newsfeeds")]
    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public void ValidateNewsfeedTitle()
    {
        if (string.IsNullOrWhiteSpace(Title))
        {
            throw new ArgumentException("Title cannot be empty");
        }
        if (Title.Length > 50)
        {
            throw new ArgumentOutOfRangeException("Title cannot be longer than 50 characters");
        }
        
    }

    public void ValidateNewsfeedText()
    {
        if (string.IsNullOrWhiteSpace(NewsfeedText))
        {
            throw new ArgumentException("Newsfeed text cannot be empty");
        }
        if (NewsfeedText.Length > 500)
        {
            throw new ArgumentOutOfRangeException("Newsfeed text cannot be longer than 500 characters");
        }
    }

    public void Validate()
    {
        ValidateNewsfeedTitle();
        ValidateNewsfeedText();
    }
}