// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GreenInspireLib.Models;

[Table("Newsfeed")]
public partial class Newsfeed
{
    [Key]
    [Column("Newsfeed_Id")]
    public int NewsfeedId { get; set; }

    [Column("Newsfeed_Image")]
    [MaxLength(1)]
    public byte[] NewsfeedImage { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Title { get; set; }

    [Required]
    [Column("Newsfeed_Text")]
    [StringLength(500)]
    [Unicode(false)]
    public string NewsfeedText { get; set; }

    [Column("Newsfeed_Timestamp", TypeName = "datetime")]
    public DateTime NewsfeedTimestamp { get; set; }

    [Column("Company_User_Id")]
    public int CompanyUserId { get; set; }

    [ForeignKey("CompanyUserId")]
    [InverseProperty("Newsfeeds")]
    public virtual CompanyUser CompanyUser { get; set; }

    [ForeignKey("NewsfeedId")]
    [InverseProperty("Newsfeeds")]
    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}